[project]
name = "clipper"
version = "0.1.0"
description = "AI video clipper"
authors = [
    { name = "kagure-nyakio", email = "kagurenyakio@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "ffmpeg-python>=0.2.0",
]

[project.scripts]
clipper = "clipper:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[[tool.mypy.overrides]]
module = ["ffmpeg.*"]
ignore_missing_imports = true

[dependency-groups]
dev = [
    "deptry>=0.25.1",
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.5",
]
